# permissions for end users to view op6apikinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: op6apikind-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: op6
    app.kubernetes.io/part-of: op6
    app.kubernetes.io/managed-by: kustomize
  name: op6apikind-viewer-role
rules:
- apiGroups:
  - op6apigroup.op6domain
  resources:
  - op6apikinds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - op6apigroup.op6domain
  resources:
  - op6apikinds/status
  verbs:
  - get
